"""create volunteer_hours table

Revision ID: fb551b6dcb64
Revises: a455f2275674
Create Date: 2026-09-05 12:11:52.929395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb551b6dcb64'
down_revision: Union[str, Sequence[str], None] = 'a455f2275674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=50), nullable=False),
    sa.Column('supervisor_name', sa.String(length=40), nullable=False),
    sa.Column('organisation_name', sa.String(length=50), nullable=False),
    sa.Column('evidence_form', sa.String(length=200), nullable=False),
    sa.Column('task_summary', sa.String(length=500), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteer_hours')
    # ### end Alembic commands ###
